// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2XThfR5XZaL-c8g4AJ1ZoDbU3j3iKj2E',
    appId: '1:813676031677:web:7fa50fe065515e6b4fd1d4',
    messagingSenderId: '813676031677',
    projectId: 'test2-ca975',
    authDomain: 'test2-ca975.firebaseapp.com',
    storageBucket: 'test2-ca975.appspot.com',
    measurementId: 'G-DX2WFQG037',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVNN1Tk7d7vnjijGvl3YZOD6qsJcDVU14',
    appId: '1:813676031677:android:75a82f294032d8304fd1d4',
    messagingSenderId: '813676031677',
    projectId: 'test2-ca975',
    storageBucket: 'test2-ca975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrP81TXp8p0kECAjo5pv4tD-raNkMiYxM',
    appId: '1:813676031677:ios:63b04b048d9ff47b4fd1d4',
    messagingSenderId: '813676031677',
    projectId: 'test2-ca975',
    storageBucket: 'test2-ca975.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrP81TXp8p0kECAjo5pv4tD-raNkMiYxM',
    appId: '1:813676031677:ios:63b04b048d9ff47b4fd1d4',
    messagingSenderId: '813676031677',
    projectId: 'test2-ca975',
    storageBucket: 'test2-ca975.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );
}
